services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development-stage
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  production:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage
    ports:
      - "80:80"
