import { Outfit} from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-outfit'
});

export const metadata = {
  title: "Ecogo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="es"
      className={`${outfit.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col pb-20 pt-6 md:pt-18 ">
        {children}
      </body>
    </html>
  );
}
